### PR TITLE
Yahboom k210 developer kit

### PR DESCRIPTION
**Pull request by jdlcdl**
### What is this PR for?
an experimental support for the Yahboom-K210-Developer-Kit board (larger than yahboom module, w/ exposed headers on front)

Note: serial port not yet resolved... have not been able to connect via terminal then interrupt or start repl (even when compiler is configured)???

Beware: this board contains wifi hardware that could be enabled if jumpers were left on connecting IO pins 13,14, and 15 to esp-wifi pins tx, rx, and en respectively.

This new unsupported board pretends to be "yahboom" so that krux code is not changed.
The `./krux` builder script would require building this board like `./krux build --unsupported maixpy_yahboom_devkit`.  It could later be flashed like a yahboom `./krux flash maixpy_yahboom` as long as it was the last binary built.

### What is the purpose of this pull request?
- [ ] Bug fix
- [ ] New feature
- [ ] Docs update
- [X] Other

### CODE REVIEW

**Comment by odudex** [comment]
Nice!
Could you do a PR of Maixpy changes? Could be directly in selfcustody's repo.

**Review by odudex — APPROVED** [review]
Great refactor, looks good to me!

**Comment by tadeubas** [comment]
Good idea to have to use `allow_unsupported` in the `krux` script. Couldn't be clearer!

**Comment by odudex** [comment]
Thank you!

**Pull request merged**
